apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: grocery-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kumaresan05/grocery-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/js/config.js
          subPath: config.js
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        imagePullPolicy: Always
        args:
          - -nginx.scrape-uri=http://localhost:80/nginx_status
        ports:
          - containerPort: 9113
            name: metrics
      volumes:
      - name: config
        configMap:
          name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: grocery-store
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31581
  - name: metrics
    port: 9113
    targetPort: 9113
